version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq_server
    ports:
      - "5672:5672"  # AMQP port for clients
      - "15672:15672" # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - backend_network

  craigslist_scraper:
    build:
      context: ./scraper_workers/craigslist_scraper
    container_name: craigslist_scraper_worker
    depends_on:
      - rabbitmq
    environment:
      RABBITMQ_HOST: rabbitmq_server # Matches the service name of RabbitMQ
      RABBITMQ_USER: user
      RABBITMQ_PASS: password
      RABBITMQ_QUEUE: property_listings_raw
      # HTTP_PROXIES: "http://proxy1.example.com:8080,http://user:pass@proxy2.example.com:3128" # Example
    networks:
      - backend_network

  postgres_db:
    image: postgis/postgis:15-3.3
    container_name: postgres_db_container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: real_estate_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database_setup:/docker-entrypoint-initdb.d # Mount init scripts
    networks:
      - backend_network
    shm_size: '1g' # Recommended for PostGIS

  elasticsearch_db:
    image: elasticsearch:8.11.0
    container_name: elasticsearch_db_container
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      discovery.type: single-node
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
      xpack.security.enabled: "false" # Ensure this is a string if YAML parses it as boolean
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - backend_network

  data_processing:
    build:
      context: ./data_processing
    container_name: data_processing_service
    depends_on:
      - rabbitmq
      - postgres_db
      - elasticsearch_db
    environment:
      RABBITMQ_URL: amqp://user:password@rabbitmq_server
      RABBITMQ_QUEUE: property_listings_raw
      POSTGRES_URL: postgresql://user:password@postgres_db:5432/real_estate_db
      ELASTICSEARCH_NODE: http://elasticsearch_db:9200
      ELASTICSEARCH_INDEX: properties
      NODE_ENV: development # Or production, depending on needs
    networks:
      - backend_network

  api_service:
    build:
      context: ./api_service
    container_name: api_service_node
    ports:
      - "3000:3000" # Expose API port to host
    environment:
      POSTGRES_URL: postgresql://user:password@postgres_db:5432/real_estate_db
      PORT: 3000
      ELASTICSEARCH_NODE: http://elasticsearch_db:9200
      ELASTICSEARCH_INDEX: properties
      REDIS_URL: redis://redis_cache_service:6379
      CACHE_TTL_PROPERTIES: "300"
      CACHE_TTL_METADATA: "600"
      RATE_LIMIT_POINTS: "100"      # Max requests per duration per IP
      RATE_LIMIT_DURATION: "60"     # Duration in seconds (e.g., 100 reqs per 60 sec)
      # RATE_LIMIT_BLOCK_DURATION: "3600" # Optional: Block duration if points consumed
      NODE_ENV: development
    depends_on:
      - postgres_db
      - elasticsearch_db
      - redis_cache_service
    networks:
      - backend_network

  redis_cache: # This service was already present, moved it up for clarity / grouping with other dbs
    image: redis:7-alpine
    container_name: redis_cache_service
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - backend_network
    restart: always

  advanced_scraper_puppeteer:
    build:
      context: ./scraper_workers/advanced_scraper_puppeteer
    container_name: advanced_scraper_puppeteer_service
    restart: 'no'
    depends_on:
      - rabbitmq
    environment:
      RABBITMQ_URL: "amqp://user:password@rabbitmq_server"
      RABBITMQ_QUEUE: "property_listings_raw"
      TARGET_URL: "http://example-dynamic-site.com/listings"
      SOURCE_NAME: "DynamicSiteScraper"
      PUPPETEER_HEADLESS: "true"
      NODE_ENV: "development"
      # HTTP_PROXIES: "http://proxy1.example.com:8080,http://user:pass@proxy2.example.com:3128"
      # DEBUG: "puppeteer:*"
    networks:
      - backend_network
    # cap_add:
    #   - SYS_ADMIN

  scheduler:
    build:
      context: ./scheduler
    container_name: scheduler_service
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./:/app/
    depends_on:
      - craigslist_scraper
      - advanced_scraper_puppeteer
    # networks:
    #   - backend_network

volumes:
  rabbitmq_data:
  postgres_data:
  elasticsearch_data:
  redis_data: # Added redis_data here

networks:
  backend_network:
    driver: bridge
